const strings = locale => {
  return {
    Home: 'خانه',
    Shop: 'فروشگاه',
    Bag: 'سبد خرید',
    Favorites: 'مورد علاقه',
    Profile: 'پروفایل',
    New: 'جدید',
    ViewAll: 'مشاهده همه',
    Sale: 'پیشنهاد شگفت انگیز',
    NewProducts: 'محصولات جدید',
    Filter: 'فیلتر',
    Compare: 'مقایسه',
    SortBy: 'مرتب سازی بر اساس',
    Popular: 'پر بازدیدترین',
    Newest: 'جدیدترین',
    CustomerReview: 'امتیاز مشتریان',
    PriceLowestToHigh: 'قیمت: از پایین ترین به بالا',
    PriceHighestToLow: 'قیمت: از بالاترین به پایین',
    Categories: 'دسته بندی ها',
    ViewAllItem: 'مشاهده همه دسته بندی ها',
    ChooseCategory: 'دسته بندی مورد نظر خود را انتخاب کنید.',
    PriceRange: 'بازه قیمت',
    Colors: 'رنگ ها',
    Apply: 'اعمال',
    Discard: 'لغو',
    RatingAndReviews: 'نظرات کاربران',
    Reviews: 'نظر',
    WriteAReview: 'نوشتن نظر',
    WhatIsYouRate: 'به این محصول چه امتیازی می دهید؟',
    PleaseShareYourOpinionAbutTheProduct:
      'نظر خود درباره محصول را به اشتراک بگذارید.',
    SendReview: 'ارسال',
    AddToCard: 'افزودن به سبد خرید',
    ProductProperties: 'مشخصات فنی',
    YouCanAlsoLikeThis: 'محصولات مشابه',
    Pictures: 'تصاویر',
    MyBag: 'سبد خرید',
    CheckOut: 'بررسی',
    Color: 'رنگ',
    Dollar: 'تومان',
    AddToFavorites: 'افزودن به مورد علاقه ها',
    DeleteFromThisList: 'حذف کردن از این لیست',
    EnterYourPromoCode: 'کد تخفیف خود را وارد کنید.',
    TotalAmount: 'جمع کل',
    ShippingAddress: 'آدرس ارسال',
    Change: 'تغییر',
    Order: 'جمع سبد خرید',
    Delivery: 'هزینه ارسال',
    Summary: 'جمع کل',
    SubmitOrder: 'پرداخت',
    ContinueShopping: 'ادامه دادن خرید',
    Success: 'خرید شما با موفقیت انجام شد.',
    YourOrderWillBeDeliveredSoon: 'سفارش شما به زودی ارسال خواهد شد.',
    ThisItemIsCurrentlySoldOut: 'متاسفانه این محصول در حال حاضر موجود نیست.',
    MyProfile: 'پروفایل',
    MyOrders: 'سفارشات من',
    AlreadyHave12Orders: 'سفارش',
    ShippingAddresses: 'آدرس های ارسال',
    Addresses: 'آدرس',
    PromoCodes: 'کدهای تخفیف',
    YouHaveSpecialPromoCodes: 'شما کدهای تخفیف خاصی دارید',
    MyReviews: 'نظرات من',
    ReviewsFor4Items: 'نظر',
    Settings: 'تنظیمات',
    Password: 'رمز عبور',
    OrderNo: 'شماره سفارش',
    TrackingNumber: 'کد پیگیری',
    Quantity: 'تعداد',
    Area: 'متراژ',
    Details: 'جزئیات',
    OrderDetails: 'جزئیات سفارش',
    Items: 'مورد',
    SquareMeters: 'متر مربع',
    OrderInformation: 'اطلاعات سفارش',
    Discount: 'تخفیف',
    LeaveFeedback: 'نوشتن بازخورد',
    PleaseWriteYourFeedbackAbutThisShop: 'بازخورد خود از این خرید را بنویسید.',
    Edit: 'ویرایش',
    UseAsTheShippingAddress: 'استفاده به عنوان آدرس ارسال',
    AddingShippingAddress: 'افزودن آدرس ارسال',
    FullName: 'نام کامل',
    Address: 'آدرس',
    City: 'شهر',
    PostalCode: 'کد پستی',
    SaveAddress: 'ذخیره آدرس',
    PersonalInformation: 'مشخصات شخصی',
    UserFullName: 'نام و نام خانوادگی',
    DateOfBirth: 'تاریخ تولد',
    PasswordChange: 'تغییر رمز عبور',
    OldPassword: 'رمز عبور قبلی',
    NewPassword: 'رمز عبور جدید',
    RepeatNewPassword: 'تکرار رمز عبور جدید',
    SavePassWord: 'ذخیره رمز عبور',
    ForgotPassword: 'رمز عبور خود را فراموش کرده اید؟',
    Login: 'ورود',
    PhoneNumber: 'شماره همراه',
    SignUp: 'ثبت نام',
    RepeatPassword: 'تکرار رمز عبور',
    SendVerifyCode: 'ارسال کد تایید',
    ForgotPasswordPage: 'فراموشی رمز عبور',
    PleaseEnterYourEmailYouWillReceiveALinkToCreateANewPasswordViaEmail:
      'لطفا شماره همراه خود را وارد نمایید. کد تایید برای شما پیامک خواهد شد.',
    AlreadyHaveAnAccount: 'قبلا ثبت نام کرده اید؟',
    Send: 'ارسال',
    Verify: 'تایید',
    PleaseEnterTheTextCodeToYourPhoneNumber:
      'لطفا کد ارسال شده به شماره همراه خود را وارد کنید.',
    VerifyCode: 'کد تایید',
    CompareBy: 'مقایسه با',
    Search: 'جستجو',
    PressBackAgainToExit: 'برای خروج دکمه بازگشت را دوباره بزنید.',
    BEHEENE: 'B E H E E N E',
    ConnectionError: 'خطا در برقراری اتصال',
    LoginError: 'شماره همراه و یا رمز عبور صحیح نمی باشد.',
    AddToBagStatus: 'محصول با موفقیت به سبد خرید شما اضافه شد.',
    ThereIsNothing: 'موردی یافت نشد.',
    YourShoppingCartIsEmpty: 'سبد خرید شما خالی است.',
    YourShippingAddressesListIsEmpty: 'لیست آدرس های ارسال شما خالی است.',
    Camera: 'دوربین',
    ChooseFromGallery: 'گالری',
    Save: 'ذخیره',
    SignOut: 'خروج',
    SignOutOfAccount: 'خروج از حساب کاربری',
    DoYouWantToSignOutOfYourAccount:
      'آیا می خواهید از حساب کاربری خود خارج شوید؟',
    Yes: 'بله',
    No: 'خیر',
    ConnectionServerError: 'خطا در برقراری اتصال با سرور',
    Accepted: 'تایید شده',
    DeliveryFromWarehouse: 'تحویل از انبار',
    Posted: 'ارسال شده',
    Delivered: 'تحویل شده',
    ThePasswordAndItsRepetitionAreNotTheSame:
      'رمز عبور و تکرار آن با هم برابر نیستند!',
    SomethingWentWrongPleaseTryAgain: 'مشکلی پیش آمده است. دوباره تلاش کنید.',
    PaymentStatus: 'وضعیت پرداخت',
    WrongCodeEntered: 'کد وارد شده اشتباه است.',
    PleaseEnterYourNewPassword: 'لطفا رمز عبور جدید خود را وارد کنید.',
    AllFieldsAreRequired: 'پر کردن تمام فیلدها الزامی است.',
    TheCellNumberEnteredIsNotCorrect: 'شماره همراه وارد شده صحیح نیست.',
    SignUpOrLogin: 'ثبت نام - ورود',
    Discounted: 'تخفیف دار',
    AddressName: 'نام آدرس',
    Province: 'استان',
    FirstSelectTheProvince: 'ابتدا استان را انتخاب کنید.',
    PasswordMustBeAtLeastEightCharactersLong:
      'رمز عبور باید حداقل هشت کاراکتر باشد.',
    ThisMobileNumberIsAlreadySelectedRegisterWithAnotherMobile:
      'این شماره موبایل قبلا استفاده شده است، با موبایل دیگری ثبت نام کنید.',
    PleaseEnterTheVerificationCodeCorrectly: 'کد تایید را به درستی وارد کنید.',
    YourPasswordHasBeenSuccessfullyChanged: 'رمز عبور شما با موفقیت تغییر کرد.',
    EnterTheArea: 'متراژ را وارد کنید.',
  };
};

export {strings};
