const strings = locale => {
  return {
    Home: 'خانه',
    Shop: 'فروشگاه',
    Bag: 'سبد خرید',
    Favorites: 'مورد علاقه',
    Profile: 'پروفایل',
    New: 'جدید',
    ViewAll: 'مشاهده همه',
    Sale: 'پیشنهاد شگفت انگیز',
    SuperSummerSale: 'حراج بزرگ زمستانی',
    NewProducts: 'محصولات جدید',
    YouHaveNeverSeenItBefore: 'شما این محصولات را تاکنون ندیده اید!',
    Filter: 'فیلتر',
    Compare: 'مقایسه',
    SortBy: 'مرتب سازی بر اساس',
    Popular: 'پر بازدیدترین',
    Newest: 'جدیدترین',
    CustomerReview: 'امتیاز مشتریان',
    PriceLowestToHigh: 'قیمت: از پایین ترین به بالا',
    PriceHighestToLow: 'قیمت: از بالاترین به پایین',
    Categories: 'دسته بندی ها',
    ViewAllItem: 'مشاهده همه دسته بندی ها',
    ChooseCategory: 'دسته بندی را انتخاب کنید',
    PriceRange: 'بازه قیمت',
    Colors: 'رنگ ها',
    Apply: 'اعمال',
    Discard: 'لغو',
    RatingAndReviews: 'نظرات کاربران',
    Reviews: 'نظر',
    WriteAReview: 'نوشتن نظر',
    WhatIsYouRate: 'به این محصول چه امتیازی می دهید؟',
    PleaseShareYourOpinionAbutTheProduct:
      'نظر خود درباره محصول را به اشتراک بگذارید.',
    SendReview: 'ارسال',
    AddToCard: 'افزودن به سبد خرید',
    ProductProperties: 'مشخصات محصول',
    YouCanAlsoLikeThis: 'محصولات مشابه',
    Pictures: 'تصاویر',
    MyBag: 'سبد خرید',
    CheckOut: 'بررسی',
    Color: 'رنگ',
    Dollar: 'تومان',
    AddToFavorites: 'افزودن به مورد علاقه ها',
    DeleteFromThisList: 'حذف کردن از این لیست',
    EnterYourPromoCode: 'کد تخفیف خود را وارد کنید',
    TotalAmount: 'جمع کل',
    ShippingAddress: 'آدرس ارسال',
    Change: 'تغییر',
    Order: 'جمع سبد خرید',
    Delivery: 'هزینه ارسال',
    Summary: 'جمع کل',
    SubmitOrder: 'ثبت سفارش',
    ContinueShopping: 'ادامه دادن خرید',
    Success: 'خرید شما با موفقیت انجام شد.',
    YourOrderWillBeDeliveredSoon: 'سفارش شما به زودی تحویل داده خواهد شد.',
    ThisItemIsCurrentlySoldOut: 'متاسفانه این محصول در حال حاضر موجود نیست',
  };
};

export {strings};
