import {createStackNavigator} from 'react-navigation';
import {
  Landing,
  Reviews,
  SingleCard,
  Bag,
  CheckOut,
  Success,
  ShippingAddresses,
  AddingShippingAddress,
  Settings,
  Login,
  SignUp,
  ForgotPassword,
  VerifyCode,
  ViewAllSale,
  ViewAllNew,
  Categories,
  ProductProperties,
  CompareBy,
  Compare,
  Search,
  SpecialCategory,
  MyOrders,
  OrderDetails,
  MyComments,
  VerifyCodeForgot,
  ChangePassword,
  ChangePasswordSettings,
} from './screens';
import {Zoom} from './components';

const RootStack = createStackNavigator(
  {
    _Landing: Landing,
    _Reviews: Reviews,
    _SingleCard: SingleCard,
    _Zoom: Zoom,
    _Bag: Bag,
    _CheckOut: CheckOut,
    _Success: Success,
    _ShippingAddresses: ShippingAddresses,
    _AddingShippingAddress: AddingShippingAddress,
    _Settings: Settings,
    _Login: Login,
    _SignUp: SignUp,
    _ForgotPassword: ForgotPassword,
    _VerifyCode: VerifyCode,
    _ViewAllSale: ViewAllSale,
    _ViewAllNew: ViewAllNew,
    _Categories: Categories,
    _ProductProperties: ProductProperties,
    _CompareBy: CompareBy,
    _Compare: Compare,
    _Search: Search,
    _SpecialCategory: SpecialCategory,
    _MyOrders: MyOrders,
    _OrderDetails: OrderDetails,
    _MyComments: MyComments,
    _VerifyCodeForgot: VerifyCodeForgot,
    _ChangePassword: ChangePassword,
    _ChangePasswordSettings: ChangePasswordSettings,
  },
  {
    initialRouteName: '_Landing',
    navigationOptions: {
      header: null,
    },
  },
);

export default RootStack;
